/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app.index'
import { Route as AppNewProposalImport } from './routes/_app.newProposal'
import { Route as AppSubmitBreakoutIndexImport } from './routes/_app.submitBreakout.index'
import { Route as AppNewProposalIndexImport } from './routes/_app.newProposal/index'
import { Route as AppProposalPropIdImport } from './routes/_app.proposal/$propId'
import { Route as AppNewProposalPropTypeIndexImport } from './routes/_app.newProposal/$propType.index'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppNewProposalRoute = AppNewProposalImport.update({
  id: '/newProposal',
  path: '/newProposal',
  getParentRoute: () => AppRoute,
} as any)

const AppSubmitBreakoutIndexRoute = AppSubmitBreakoutIndexImport.update({
  id: '/submitBreakout/',
  path: '/submitBreakout/',
  getParentRoute: () => AppRoute,
} as any)

const AppNewProposalIndexRoute = AppNewProposalIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNewProposalRoute,
} as any)

const AppProposalPropIdRoute = AppProposalPropIdImport.update({
  id: '/proposal/$propId',
  path: '/proposal/$propId',
  getParentRoute: () => AppRoute,
} as any)

const AppNewProposalPropTypeIndexRoute =
  AppNewProposalPropTypeIndexImport.update({
    id: '/$propType/',
    path: '/$propType/',
    getParentRoute: () => AppNewProposalRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/newProposal': {
      id: '/_app/newProposal'
      path: '/newProposal'
      fullPath: '/newProposal'
      preLoaderRoute: typeof AppNewProposalImport
      parentRoute: typeof AppImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/proposal/$propId': {
      id: '/_app/proposal/$propId'
      path: '/proposal/$propId'
      fullPath: '/proposal/$propId'
      preLoaderRoute: typeof AppProposalPropIdImport
      parentRoute: typeof AppImport
    }
    '/_app/newProposal/': {
      id: '/_app/newProposal/'
      path: '/'
      fullPath: '/newProposal/'
      preLoaderRoute: typeof AppNewProposalIndexImport
      parentRoute: typeof AppNewProposalImport
    }
    '/_app/submitBreakout/': {
      id: '/_app/submitBreakout/'
      path: '/submitBreakout'
      fullPath: '/submitBreakout'
      preLoaderRoute: typeof AppSubmitBreakoutIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/newProposal/$propType/': {
      id: '/_app/newProposal/$propType/'
      path: '/$propType'
      fullPath: '/newProposal/$propType'
      preLoaderRoute: typeof AppNewProposalPropTypeIndexImport
      parentRoute: typeof AppNewProposalImport
    }
  }
}

// Create and export the route tree

interface AppNewProposalRouteChildren {
  AppNewProposalIndexRoute: typeof AppNewProposalIndexRoute
  AppNewProposalPropTypeIndexRoute: typeof AppNewProposalPropTypeIndexRoute
}

const AppNewProposalRouteChildren: AppNewProposalRouteChildren = {
  AppNewProposalIndexRoute: AppNewProposalIndexRoute,
  AppNewProposalPropTypeIndexRoute: AppNewProposalPropTypeIndexRoute,
}

const AppNewProposalRouteWithChildren = AppNewProposalRoute._addFileChildren(
  AppNewProposalRouteChildren,
)

interface AppRouteChildren {
  AppNewProposalRoute: typeof AppNewProposalRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppProposalPropIdRoute: typeof AppProposalPropIdRoute
  AppSubmitBreakoutIndexRoute: typeof AppSubmitBreakoutIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNewProposalRoute: AppNewProposalRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppProposalPropIdRoute: AppProposalPropIdRoute,
  AppSubmitBreakoutIndexRoute: AppSubmitBreakoutIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/newProposal': typeof AppNewProposalRouteWithChildren
  '/': typeof AppIndexRoute
  '/proposal/$propId': typeof AppProposalPropIdRoute
  '/newProposal/': typeof AppNewProposalIndexRoute
  '/submitBreakout': typeof AppSubmitBreakoutIndexRoute
  '/newProposal/$propType': typeof AppNewProposalPropTypeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/proposal/$propId': typeof AppProposalPropIdRoute
  '/newProposal': typeof AppNewProposalIndexRoute
  '/submitBreakout': typeof AppSubmitBreakoutIndexRoute
  '/newProposal/$propType': typeof AppNewProposalPropTypeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/newProposal': typeof AppNewProposalRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/proposal/$propId': typeof AppProposalPropIdRoute
  '/_app/newProposal/': typeof AppNewProposalIndexRoute
  '/_app/submitBreakout/': typeof AppSubmitBreakoutIndexRoute
  '/_app/newProposal/$propType/': typeof AppNewProposalPropTypeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/newProposal'
    | '/'
    | '/proposal/$propId'
    | '/newProposal/'
    | '/submitBreakout'
    | '/newProposal/$propType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/proposal/$propId'
    | '/newProposal'
    | '/submitBreakout'
    | '/newProposal/$propType'
  id:
    | '__root__'
    | '/_app'
    | '/_app/newProposal'
    | '/_app/'
    | '/_app/proposal/$propId'
    | '/_app/newProposal/'
    | '/_app/submitBreakout/'
    | '/_app/newProposal/$propType/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/newProposal",
        "/_app/",
        "/_app/proposal/$propId",
        "/_app/submitBreakout/"
      ]
    },
    "/_app/newProposal": {
      "filePath": "_app.newProposal.tsx",
      "parent": "/_app",
      "children": [
        "/_app/newProposal/",
        "/_app/newProposal/$propType/"
      ]
    },
    "/_app/": {
      "filePath": "_app.index.tsx",
      "parent": "/_app"
    },
    "/_app/proposal/$propId": {
      "filePath": "_app.proposal/$propId.tsx",
      "parent": "/_app"
    },
    "/_app/newProposal/": {
      "filePath": "_app.newProposal/index.tsx",
      "parent": "/_app/newProposal"
    },
    "/_app/submitBreakout/": {
      "filePath": "_app.submitBreakout.index.tsx",
      "parent": "/_app"
    },
    "/_app/newProposal/$propType/": {
      "filePath": "_app.newProposal/$propType.index.tsx",
      "parent": "/_app/newProposal"
    }
  }
}
ROUTE_MANIFEST_END */
