/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSubmitBreakoutRouteImport } from './routes/_app.submitBreakout'
import { Route as AppProposalsRouteImport } from './routes/_app.proposals'
import { Route as AppNewProposalRouteImport } from './routes/_app.newProposal'
import { Route as AppChildRespectRouteImport } from './routes/_app.childRespect'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppSubmitBreakoutIndexRouteImport } from './routes/_app.submitBreakout/index'
import { Route as AppProposalsIndexRouteImport } from './routes/_app.proposals/index'
import { Route as AppNewProposalIndexRouteImport } from './routes/_app.newProposal/index'
import { Route as AppProposalsPropIdRouteImport } from './routes/_app.proposals/$propId'
import { Route as AppChildRespectAwardsRouteImport } from './routes/_app.childRespect/awards'
import { Route as AppChildRespectAccountsRouteImport } from './routes/_app.childRespect/accounts'
import { Route as AppAboutUserGuideRouteImport } from './routes/_app.about/userGuide'
import { Route as AppAboutIntentRouteImport } from './routes/_app.about/intent'
import { Route as AppAboutCommunitiesRouteImport } from './routes/_app.about/communities'
import { Route as AppAboutAppStateRouteImport } from './routes/_app.about/appState'
import { Route as AppNewProposalPropTypeIndexRouteImport } from './routes/_app.newProposal/$propType.index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmitBreakoutRoute = AppSubmitBreakoutRouteImport.update({
  id: '/submitBreakout',
  path: '/submitBreakout',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppNewProposalRoute = AppNewProposalRouteImport.update({
  id: '/newProposal',
  path: '/newProposal',
  getParentRoute: () => AppRoute,
} as any)
const AppChildRespectRoute = AppChildRespectRouteImport.update({
  id: '/childRespect',
  path: '/childRespect',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmitBreakoutIndexRoute = AppSubmitBreakoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSubmitBreakoutRoute,
} as any)
const AppProposalsIndexRoute = AppProposalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProposalsRoute,
} as any)
const AppNewProposalIndexRoute = AppNewProposalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNewProposalRoute,
} as any)
const AppProposalsPropIdRoute = AppProposalsPropIdRouteImport.update({
  id: '/$propId',
  path: '/$propId',
  getParentRoute: () => AppProposalsRoute,
} as any)
const AppChildRespectAwardsRoute = AppChildRespectAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AppChildRespectRoute,
} as any)
const AppChildRespectAccountsRoute = AppChildRespectAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppChildRespectRoute,
} as any)
const AppAboutUserGuideRoute = AppAboutUserGuideRouteImport.update({
  id: '/userGuide',
  path: '/userGuide',
  getParentRoute: () => AppAboutRoute,
} as any)
const AppAboutIntentRoute = AppAboutIntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => AppAboutRoute,
} as any)
const AppAboutCommunitiesRoute = AppAboutCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AppAboutRoute,
} as any)
const AppAboutAppStateRoute = AppAboutAppStateRouteImport.update({
  id: '/appState',
  path: '/appState',
  getParentRoute: () => AppAboutRoute,
} as any)
const AppNewProposalPropTypeIndexRoute =
  AppNewProposalPropTypeIndexRouteImport.update({
    id: '/$propType/',
    path: '/$propType/',
    getParentRoute: () => AppNewProposalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof AppAboutRouteWithChildren
  '/childRespect': typeof AppChildRespectRouteWithChildren
  '/newProposal': typeof AppNewProposalRouteWithChildren
  '/proposals': typeof AppProposalsRouteWithChildren
  '/submitBreakout': typeof AppSubmitBreakoutRouteWithChildren
  '/': typeof AppIndexRoute
  '/about/appState': typeof AppAboutAppStateRoute
  '/about/communities': typeof AppAboutCommunitiesRoute
  '/about/intent': typeof AppAboutIntentRoute
  '/about/userGuide': typeof AppAboutUserGuideRoute
  '/childRespect/accounts': typeof AppChildRespectAccountsRoute
  '/childRespect/awards': typeof AppChildRespectAwardsRoute
  '/proposals/$propId': typeof AppProposalsPropIdRoute
  '/newProposal/': typeof AppNewProposalIndexRoute
  '/proposals/': typeof AppProposalsIndexRoute
  '/submitBreakout/': typeof AppSubmitBreakoutIndexRoute
  '/newProposal/$propType': typeof AppNewProposalPropTypeIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRouteWithChildren
  '/childRespect': typeof AppChildRespectRouteWithChildren
  '/': typeof AppIndexRoute
  '/about/appState': typeof AppAboutAppStateRoute
  '/about/communities': typeof AppAboutCommunitiesRoute
  '/about/intent': typeof AppAboutIntentRoute
  '/about/userGuide': typeof AppAboutUserGuideRoute
  '/childRespect/accounts': typeof AppChildRespectAccountsRoute
  '/childRespect/awards': typeof AppChildRespectAwardsRoute
  '/proposals/$propId': typeof AppProposalsPropIdRoute
  '/newProposal': typeof AppNewProposalIndexRoute
  '/proposals': typeof AppProposalsIndexRoute
  '/submitBreakout': typeof AppSubmitBreakoutIndexRoute
  '/newProposal/$propType': typeof AppNewProposalPropTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRouteWithChildren
  '/_app/childRespect': typeof AppChildRespectRouteWithChildren
  '/_app/newProposal': typeof AppNewProposalRouteWithChildren
  '/_app/proposals': typeof AppProposalsRouteWithChildren
  '/_app/submitBreakout': typeof AppSubmitBreakoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/about/appState': typeof AppAboutAppStateRoute
  '/_app/about/communities': typeof AppAboutCommunitiesRoute
  '/_app/about/intent': typeof AppAboutIntentRoute
  '/_app/about/userGuide': typeof AppAboutUserGuideRoute
  '/_app/childRespect/accounts': typeof AppChildRespectAccountsRoute
  '/_app/childRespect/awards': typeof AppChildRespectAwardsRoute
  '/_app/proposals/$propId': typeof AppProposalsPropIdRoute
  '/_app/newProposal/': typeof AppNewProposalIndexRoute
  '/_app/proposals/': typeof AppProposalsIndexRoute
  '/_app/submitBreakout/': typeof AppSubmitBreakoutIndexRoute
  '/_app/newProposal/$propType/': typeof AppNewProposalPropTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/childRespect'
    | '/newProposal'
    | '/proposals'
    | '/submitBreakout'
    | '/'
    | '/about/appState'
    | '/about/communities'
    | '/about/intent'
    | '/about/userGuide'
    | '/childRespect/accounts'
    | '/childRespect/awards'
    | '/proposals/$propId'
    | '/newProposal/'
    | '/proposals/'
    | '/submitBreakout/'
    | '/newProposal/$propType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/childRespect'
    | '/'
    | '/about/appState'
    | '/about/communities'
    | '/about/intent'
    | '/about/userGuide'
    | '/childRespect/accounts'
    | '/childRespect/awards'
    | '/proposals/$propId'
    | '/newProposal'
    | '/proposals'
    | '/submitBreakout'
    | '/newProposal/$propType'
  id:
    | '__root__'
    | '/_app'
    | '/_app/about'
    | '/_app/childRespect'
    | '/_app/newProposal'
    | '/_app/proposals'
    | '/_app/submitBreakout'
    | '/_app/'
    | '/_app/about/appState'
    | '/_app/about/communities'
    | '/_app/about/intent'
    | '/_app/about/userGuide'
    | '/_app/childRespect/accounts'
    | '/_app/childRespect/awards'
    | '/_app/proposals/$propId'
    | '/_app/newProposal/'
    | '/_app/proposals/'
    | '/_app/submitBreakout/'
    | '/_app/newProposal/$propType/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submitBreakout': {
      id: '/_app/submitBreakout'
      path: '/submitBreakout'
      fullPath: '/submitBreakout'
      preLoaderRoute: typeof AppSubmitBreakoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proposals': {
      id: '/_app/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/newProposal': {
      id: '/_app/newProposal'
      path: '/newProposal'
      fullPath: '/newProposal'
      preLoaderRoute: typeof AppNewProposalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/childRespect': {
      id: '/_app/childRespect'
      path: '/childRespect'
      fullPath: '/childRespect'
      preLoaderRoute: typeof AppChildRespectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submitBreakout/': {
      id: '/_app/submitBreakout/'
      path: '/'
      fullPath: '/submitBreakout/'
      preLoaderRoute: typeof AppSubmitBreakoutIndexRouteImport
      parentRoute: typeof AppSubmitBreakoutRoute
    }
    '/_app/proposals/': {
      id: '/_app/proposals/'
      path: '/'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AppProposalsIndexRouteImport
      parentRoute: typeof AppProposalsRoute
    }
    '/_app/newProposal/': {
      id: '/_app/newProposal/'
      path: '/'
      fullPath: '/newProposal/'
      preLoaderRoute: typeof AppNewProposalIndexRouteImport
      parentRoute: typeof AppNewProposalRoute
    }
    '/_app/proposals/$propId': {
      id: '/_app/proposals/$propId'
      path: '/$propId'
      fullPath: '/proposals/$propId'
      preLoaderRoute: typeof AppProposalsPropIdRouteImport
      parentRoute: typeof AppProposalsRoute
    }
    '/_app/childRespect/awards': {
      id: '/_app/childRespect/awards'
      path: '/awards'
      fullPath: '/childRespect/awards'
      preLoaderRoute: typeof AppChildRespectAwardsRouteImport
      parentRoute: typeof AppChildRespectRoute
    }
    '/_app/childRespect/accounts': {
      id: '/_app/childRespect/accounts'
      path: '/accounts'
      fullPath: '/childRespect/accounts'
      preLoaderRoute: typeof AppChildRespectAccountsRouteImport
      parentRoute: typeof AppChildRespectRoute
    }
    '/_app/about/userGuide': {
      id: '/_app/about/userGuide'
      path: '/userGuide'
      fullPath: '/about/userGuide'
      preLoaderRoute: typeof AppAboutUserGuideRouteImport
      parentRoute: typeof AppAboutRoute
    }
    '/_app/about/intent': {
      id: '/_app/about/intent'
      path: '/intent'
      fullPath: '/about/intent'
      preLoaderRoute: typeof AppAboutIntentRouteImport
      parentRoute: typeof AppAboutRoute
    }
    '/_app/about/communities': {
      id: '/_app/about/communities'
      path: '/communities'
      fullPath: '/about/communities'
      preLoaderRoute: typeof AppAboutCommunitiesRouteImport
      parentRoute: typeof AppAboutRoute
    }
    '/_app/about/appState': {
      id: '/_app/about/appState'
      path: '/appState'
      fullPath: '/about/appState'
      preLoaderRoute: typeof AppAboutAppStateRouteImport
      parentRoute: typeof AppAboutRoute
    }
    '/_app/newProposal/$propType/': {
      id: '/_app/newProposal/$propType/'
      path: '/$propType'
      fullPath: '/newProposal/$propType'
      preLoaderRoute: typeof AppNewProposalPropTypeIndexRouteImport
      parentRoute: typeof AppNewProposalRoute
    }
  }
}

interface AppAboutRouteChildren {
  AppAboutAppStateRoute: typeof AppAboutAppStateRoute
  AppAboutCommunitiesRoute: typeof AppAboutCommunitiesRoute
  AppAboutIntentRoute: typeof AppAboutIntentRoute
  AppAboutUserGuideRoute: typeof AppAboutUserGuideRoute
}

const AppAboutRouteChildren: AppAboutRouteChildren = {
  AppAboutAppStateRoute: AppAboutAppStateRoute,
  AppAboutCommunitiesRoute: AppAboutCommunitiesRoute,
  AppAboutIntentRoute: AppAboutIntentRoute,
  AppAboutUserGuideRoute: AppAboutUserGuideRoute,
}

const AppAboutRouteWithChildren = AppAboutRoute._addFileChildren(
  AppAboutRouteChildren,
)

interface AppChildRespectRouteChildren {
  AppChildRespectAccountsRoute: typeof AppChildRespectAccountsRoute
  AppChildRespectAwardsRoute: typeof AppChildRespectAwardsRoute
}

const AppChildRespectRouteChildren: AppChildRespectRouteChildren = {
  AppChildRespectAccountsRoute: AppChildRespectAccountsRoute,
  AppChildRespectAwardsRoute: AppChildRespectAwardsRoute,
}

const AppChildRespectRouteWithChildren = AppChildRespectRoute._addFileChildren(
  AppChildRespectRouteChildren,
)

interface AppNewProposalRouteChildren {
  AppNewProposalIndexRoute: typeof AppNewProposalIndexRoute
  AppNewProposalPropTypeIndexRoute: typeof AppNewProposalPropTypeIndexRoute
}

const AppNewProposalRouteChildren: AppNewProposalRouteChildren = {
  AppNewProposalIndexRoute: AppNewProposalIndexRoute,
  AppNewProposalPropTypeIndexRoute: AppNewProposalPropTypeIndexRoute,
}

const AppNewProposalRouteWithChildren = AppNewProposalRoute._addFileChildren(
  AppNewProposalRouteChildren,
)

interface AppProposalsRouteChildren {
  AppProposalsPropIdRoute: typeof AppProposalsPropIdRoute
  AppProposalsIndexRoute: typeof AppProposalsIndexRoute
}

const AppProposalsRouteChildren: AppProposalsRouteChildren = {
  AppProposalsPropIdRoute: AppProposalsPropIdRoute,
  AppProposalsIndexRoute: AppProposalsIndexRoute,
}

const AppProposalsRouteWithChildren = AppProposalsRoute._addFileChildren(
  AppProposalsRouteChildren,
)

interface AppSubmitBreakoutRouteChildren {
  AppSubmitBreakoutIndexRoute: typeof AppSubmitBreakoutIndexRoute
}

const AppSubmitBreakoutRouteChildren: AppSubmitBreakoutRouteChildren = {
  AppSubmitBreakoutIndexRoute: AppSubmitBreakoutIndexRoute,
}

const AppSubmitBreakoutRouteWithChildren =
  AppSubmitBreakoutRoute._addFileChildren(AppSubmitBreakoutRouteChildren)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRouteWithChildren
  AppChildRespectRoute: typeof AppChildRespectRouteWithChildren
  AppNewProposalRoute: typeof AppNewProposalRouteWithChildren
  AppProposalsRoute: typeof AppProposalsRouteWithChildren
  AppSubmitBreakoutRoute: typeof AppSubmitBreakoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRouteWithChildren,
  AppChildRespectRoute: AppChildRespectRouteWithChildren,
  AppNewProposalRoute: AppNewProposalRouteWithChildren,
  AppProposalsRoute: AppProposalsRouteWithChildren,
  AppSubmitBreakoutRoute: AppSubmitBreakoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
